-- chat.timeline_entries: the conversation timeline's typed entries (1kg.4.2,
-- slice A). This file's number is written nowhere else in it: the lead
-- renumbers a migration at merge when a parallel bead takes the number first.
--
-- Pure expansion: one new table and its indexes. Nothing that exists is read
-- for rewriting, backfilled, migrated or deleted. The release running right now
-- neither reads nor writes this table, so it keeps working against a migrated
-- database (docs/migrations.md section 3), and a roll-forward after a rollback
-- loses nothing: every turn the older build served left its chat.messages rows,
-- and the read model adapts those.
--
-- ONE ROW PER EXCHANGE, written after the answer, best-effort, by POST /chat:
-- the validated wire entry (service/workbench_contracts.py) is the payload. A
-- conversation nobody has used since the deploy has no rows here and still
-- reads back completely, from its legacy rows.
--
-- THE ROW IS THE AUTHORITY ON IDENTITY AND ON TIME. entry_id and created_at are
-- columns and the payload repeats them; service/timeline_store.py refuses an
-- entry whose payload disagrees with them before any statement runs, and every
-- read goes through entry_or_opaque, which serves a placeholder for a payload
-- that names another entry's id.
--
-- entry_id IS MINTED, NEVER SEQUENTIAL (SEC-4): `ent_` and 128 CSPRNG bits. Its
-- CHECK is generated by service.timeline_store.entry_id_check_regex(), and
-- tests/test_timeline_db.py holds the SQL to it. seq is not an identifier and
-- never leaves the server except inside an opaque cursor: it only makes the
-- ordering key total, because created_at alone is not unique.
--
-- THE KIND LIST IS AS OF THIS MIGRATION. A kind added after it needs its own
-- migration, because a released migration is never edited.
--
-- THE TWO LINK COLUMNS stop a turn from rendering twice: a chat.messages row
-- that an entry names is not adapted again. One legacy row is covered by at
-- most one entry, which the two partial unique indexes enforce.
--
-- conversation_id IS VALIDATED, unlike 0001's NOT VALID messages edge: the table
-- is new, so there is no legacy row to spare. An entry goes with its
-- conversation, as chat.messages and chat.attachments do. There is no campaign
-- column: an entry belongs to a conversation, and a conversation to a user.
--
-- NO HASH, DIGEST OR FINGERPRINT of any text is stored, here or anywhere (ED-26).

CREATE TABLE chat.timeline_entries (
  entry_id             TEXT        PRIMARY KEY CHECK (entry_id ~ '^ent_[A-Za-z0-9_-]{22,60}$'),
  conversation_id      TEXT        NOT NULL REFERENCES chat.conversations (conversation_id) ON DELETE CASCADE,
  entry_kind           TEXT        NOT NULL CHECK (entry_kind IN ('chat', 'tool', 'edit', 'session_divider', 'opaque')),
  schema_version       INTEGER     NOT NULL,
  created_at           TIMESTAMPTZ NOT NULL,
  seq                  BIGSERIAL   NOT NULL,
  payload              JSONB       NOT NULL,
  user_message_id      BIGINT      REFERENCES chat.messages (id) ON DELETE CASCADE,
  assistant_message_id BIGINT      REFERENCES chat.messages (id) ON DELETE CASCADE
);

-- The page read, newest first by the total key, inside one conversation.
CREATE INDEX timeline_entries_page_idx
  ON chat.timeline_entries (conversation_id, created_at DESC, seq DESC);

-- One legacy row is covered by at most one entry.
CREATE UNIQUE INDEX timeline_entries_user_message_uidx
  ON chat.timeline_entries (user_message_id) WHERE user_message_id IS NOT NULL;
CREATE UNIQUE INDEX timeline_entries_assistant_message_uidx
  ON chat.timeline_entries (assistant_message_id) WHERE assistant_message_id IS NOT NULL;

-- DELIBERATELY BROKEN (1): the conversation edge no longer cascades.
ALTER TABLE chat.timeline_entries DROP CONSTRAINT timeline_entries_conversation_id_fkey,
  ADD CONSTRAINT timeline_entries_conversation_id_fkey
  FOREIGN KEY (conversation_id) REFERENCES chat.conversations (conversation_id);
